### PR TITLE
switch search.cpan.org URLs to metacpan.org

### PR DESCRIPTION
**Pull request by karenetheridge**
as mentioned in #73

### CODE REVIEW

**Comment by timbunce** [comment]
Thanks so much@karenetheridge, I really appreciate it. However, I beat you to it by a few hours in 1716369!

**Comment by jandubois** [comment]
> Thanks so much@karenetheridge, I really appreciate it. However, I beat you to it by a few hours in 1716369!

Except your change didn't update all the test files, so master is now failing on Travis, in turn letting further pull requests fail as well.  You should still merge this PR to get the tests fixed up too.

**Comment by karenetheridge** [comment]
Doh! I'll fix that up tonight; many apologies!

**Comment by karenetheridge** [comment]
(sorry again, I misread Jan's comment.)

**Comment by timbunce** [comment]
Merged. Thanks!

**Comment by jandubois** [comment]
> Merged. Thanks!

Thanks, I've rebased #75 on top of this, and it now passes Travis as well.

**Pull request merged**
