### PR TITLE
Gh 168 longdouble

### PR DESCRIPTION
**Pull request by jkeenan**
For issue https://github.com/timbunce/devel-nytprof/issues/168 -- once p.r. https://github.com/timbunce/devel-nytprof/pull/171 has been merged.

### CODE REVIEW

**Comment by jkeenan** [comment]
@eserte, if you get a chance, could you try this p.r. out on any of your Linux or FreeBSD uselongdouble builds?

Thank you very much.
Jim Keenan

**Comment by eserte** [comment]
I tried 87c675490fceb7704bceb6127e6d39e64509c746 on a `-Duselongdouble` system and test suite passed.

**Comment by jkeenan** [comment]
@timbunce, any concerns about merging this into master?

Thanks.
jimk

**Review by timbunce — APPROVED** [review]

**Comment by jkeenan** [comment]
Merged into master in commit 49045f6e65c41ce2a3ec4623e8dc99a8a71220f6

**Pull request closed without merging**
